version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    container_name: RetailARVA.Mongo
    networks: 
      - retailARVA
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - ENVIRONMENT=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=retailarvadb
      - USE_GROQ=False
      - USE_OLLAMA=True
      - USE_GEMINI=False
      - USE_HUGGINGFACE_EMBEDDING=False
      - USE_GOOGLE_EMBEDDING=False
      - USE_OLLAMA_EMBEDDING=True
      - OLLAMA_URL=http://172.21.174.131:11434
      - OLLAMA_MODEL_ID=llama3.1:latest
      - OLLAMA_EMBEDDING_MODEL_ID=nomic-embed-text:latest
      - CLASSIFICATION_MODEL_ID=deepseek-r1:1.5b
      - TTS_INPUT_PARSER_MODEL_ID=gemma3:4b-it-qat
      - RECOMMENDATION_MODEL_ID=llama3.1:latest
      - GEMINI_MODEL_ID=gemini-1.5-flash
      - GEMINI_EMBEDDING_MODEL_ID=llama3.1:latest
      - GOOGLE_GENERATIVE_LANGUAGE_API_KEY=[GEMINI_API_KEY]
      - GROQ_API_KEY=[GROQ_API_KEY]
      - GROQ_MODEL_ID=llama-3.1-8b-instant
      - HUGGINGFACE_EMBEDDING_MODEL_ID=BAAI/bge-large-en-v1.5
      - QDRANT_API_KEY=[QDRANT_API_KEY]
      - QDRANT_CLUSTER_URL=https://27c6018a-d381-49b4-aef4-e922ce3eea85.us-west-2-0.aws.cloud.qdrant.io
      - ELEVENLABS_API_KEY=[ELEVENLABS_API_KEY]
      - GOOGLE_APPLICATION_CREDENTIALS=C:\\Users\\dinit\\Documents\\Research\\Development\\test-playground\\retailarva-6169e9007515.json
      - GRADIO_URL=http://127.0.0.1:7860
      - GRADIO_PORT=7860

      - NGROK_AUTH_TOKEN=[NGROK_AUTH_TOKEN]
      - NGROK_STATIC_DOMAIN=alert-evolved-chicken.ngrok-free.app
      - NGROK_API_KEY=[NGROK_API_KEY]

      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_API_KEY=[LANGSMITH_API_KEY]
      - LANGSMITH_PROJECT=retailarva-deployment
    volumes:
      - retailarva-data:/app/src/data
    container_name: RetailARVA.Api
    networks: 
      - retailARVA
volumes:
  retailarva-data:
  mongo-data:
networks:
  retailARVA:
