version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    container_name: RetailARVA.Mongo
    networks: 
      - retailARVA
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - ENVIRONMENT=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=retailarvadb
      - USE_GROQ=False
      - USE_OLLAMA=True
      - USE_GEMINI=False
      - USE_HUGGINGFACE_EMBEDDING=False
      - USE_GOOGLE_EMBEDDING=False
      - USE_OLLAMA_EMBEDDING=True
      - OLLAMA_URL=http://172.21.174.131:11434
      - OLLAMA_MODEL_ID=llama3.1:latest
      - OLLAMA_EMBEDDING_MODEL_ID=nomic-embed-text:latest
      - CLASSIFICATION_MODEL_ID=deepseek-r1:1.5b
      - TTS_INPUT_PARSER_MODEL_ID=gemma3:4b-it-qat
      - RECOMMENDATION_MODEL_ID=llama3.1:latest
      - GEMINI_MODEL_ID=gemini-1.5-flash
      - GEMINI_EMBEDDING_MODEL_ID=llama3.1:latest
      - GOOGLE_GENERATIVE_LANGUAGE_API_KEY=AIzaSyDpcYeeReEC_IdaiNRtMJLfqTJpX74ZtLI
      - GROQ_API_KEY=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
      - GROQ_MODEL_ID=llama-3.1-8b-instant
      - HUGGINGFACE_EMBEDDING_MODEL_ID=BAAI/bge-large-en-v1.5
      - QDRANT_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.iB5o-6sSQPdGDJfljEvc9cV73H7dy-0AmByR9-VBVN4
      - QDRANT_CLUSTER_URL=https://fdda17ab-8e55-4273-a1b2-61227eaf0835.europe-west3-0.gcp.cloud.qdrant.io
      - ELEVENLABS_API_KEY=sk_b0206ca0a7d97fa2b60ae41448b7f47e02872aec6d6cb65f
      - GOOGLE_APPLICATION_CREDENTIALS=C:\\Users\\dinit\\Documents\\Research\\Development\\test-playground\\retailarva-6169e9007515.json
      - GRADIO_URL=http://127.0.0.1:7860
      - GRADIO_PORT=7860

      - NGROK_AUTH_TOKEN=2pLD51lUVLQIOklGiSazGnQ7zLr_795mWrmQJAQ81AteoLCVT
      - NGROK_STATIC_DOMAIN=alert-evolved-chicken.ngrok-free.app
      - NGROK_API_KEY=2pLIqaJvCW1wiY5H1ZO6TUES8nt_73Jvh7frCqNjS6vVVVBKh

      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_API_KEY=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
      - LANGSMITH_PROJECT=retailarva-deployment
    volumes:
      - retailarva-data:/app/src/data
    container_name: RetailARVA.Api
    networks: 
      - retailARVA
volumes:
  retailarva-data:
  mongo-data:
networks:
  retailARVA:
